### ISSUE TITLE
Twitter API example fails with a Null Pointer Exception

### ISSUE THREAD

**Issue by priav03** [scribejava/scribejava#526] opened 2014-12-19 07:07 UTC
I copied the sample code to a new class file. Replaced consumer key and consumer key secret with the key and secret supplied to me by Twitter. I executed the program and received the following error message.

=== Twitter's OAuth Workflow ===

Fetching the Request Token...
Exception in thread "main" org.scribe.exceptions.OAuthSignatureException: Error while signing string: POST&http%3A%2F%2Fapi.twitter.com%2Foauth%2Frequest_token&oauth_callback%3Doob%26oauth_consumer_key%3D******************************%26oauth_nonce%3D2959459152%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1418972664%26oauth_version%3D1.0
    at org.scribe.services.HMACSha1SignatureService.getSignature(HMACSha1SignatureService.java:36)
    at org.scribe.oauth.OAuth10aServiceImpl.getSignature(OAuth10aServiceImpl.java:145)
    at org.scribe.oauth.OAuth10aServiceImpl.addOAuthParams(OAuth10aServiceImpl.java:75)
    at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:55)
    at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:40)
    at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:45)
    at Tweets.main(Tweets.java:44)
Caused by: java.lang.NullPointerException
    at javax.xml.bind.DatatypeConverter.printBase64Binary(DatatypeConverter.java:547)
    at org.scribe.services.DatatypeConverterEncoder.encode(DatatypeConverterEncoder.java:10)
    at org.scribe.services.HMACSha1SignatureService.bytesToBase64String(HMACSha1SignatureService.java:51)
    at org.scribe.services.HMACSha1SignatureService.doSign(HMACSha1SignatureService.java:46)
    at org.scribe.services.HMACSha1SignatureService.getSignature(HMACSha1SignatureService.java:32)
    ... 6 more

**Comment by rkand4** [comment] 2015-04-23 00:19
I am facing the same issue. Did you find the solution to this ?

**Comment by fernandezpablo85** [comment] 2015-07-29 15:40
This seems a JDK lib issue, try including commons-codec in your classpath so scribe uses the Base64 encoder from that package.

**Comment by fernandezpablo85** [comment] 2015-07-29 15:40
Also, can you check that the tests pass on your version of the JDK? which version is it?

**Comment by agomezmoron** [comment] 2015-11-17 17:06
Hi,

It was a JAXB issue [1]. According with [2], the issue was resolved with JAXB 2.2.4, which was integrated into 1.7.  Please, check your JAXB and JDK version.

[1] https://java.net/jira/browse/JAXB-860
[2] http://stackoverflow.com/questions/12498256/why-the-npe-using-static-method-of-datatypeconverter

**Comment by kullfar** [comment] 2017-11-22 14:59
It seems, the issue is quite outdated and not relevant to the current state of source code.
If no one interested, I will close issue in one month

**Closed** 2018-01-10 10:32 UTC
